### ISSUE TITLE
Could you sent me some API key omdbapi to test this App?. Thanks. I try to get Api key in Omdapi but i have this error

### ISSUE THREAD

**Issue by helloo0-0oworld** [azamsharp/Movies-App-Flutter-MVVM#1]
![Screen Shot 2020-09-20 at 6 44 19 PM](https://user-images.githubusercontent.com/32776884/93727758-7faad600-fb71-11ea-957d-b15cb99890b1.png)

**Comment by helloo0-0oword** [comment]
sorry

**Comment by clockwiser** [comment]
omdbapi site has problem. Not work at all.
